-- MySQL Script generated by MySQL Workbench
-- 03/01/16 10:58:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET latin1 ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`producto` (
  `IdProducto` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `Tipo_producto` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Precio` DECIMAL(6,2) NULL DEFAULT NULL COMMENT '',
  `Cantidad` INT(11) NULL DEFAULT NULL COMMENT '',
  `Imagen` VARCHAR(300) NOT NULL COMMENT '',
  PRIMARY KEY (`IdProducto`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `proyecto`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`usuarios` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `Username` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Password` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Email` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `Actividad` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Tipo` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Dni_usuario` VARCHAR(9) NULL DEFAULT NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Apellidos` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Cpostal` INT(5) NULL DEFAULT NULL COMMENT '',
  `Telefono` INT(9) NULL DEFAULT NULL COMMENT '',
  `Sexo` VARCHAR(6) NULL DEFAULT NULL COMMENT '',
  `FNacimiento` DATE NULL DEFAULT NULL COMMENT '',
  `Direccion` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idusuario`)  COMMENT '',
  UNIQUE INDEX `Dni_usuario_UNIQUE` (`Dni_usuario` ASC)  COMMENT '',
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `proyecto`.`cesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`cesta` (
  `Usuarios_idusuario` INT(11) NOT NULL COMMENT '',
  `Producto_IdProducto` INT(11) NOT NULL COMMENT '',
  `Cantidad` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`Usuarios_idusuario`, `Producto_IdProducto`)  COMMENT '',
  INDEX `fk_Cesta_Producto1_idx` (`Producto_IdProducto` ASC)  COMMENT '',
  CONSTRAINT `fk_Cesta_Producto1`
    FOREIGN KEY (`Producto_IdProducto`)
    REFERENCES `proyecto`.`producto` (`IdProducto`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cesta_Usuarios1`
    FOREIGN KEY (`Usuarios_idusuario`)
    REFERENCES `proyecto`.`usuarios` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `proyecto`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`pedidos` (
  `Num_pedido` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `Usuario_idusuario` INT(11) NOT NULL COMMENT '',
  `Fecha_pedido` DATE NULL DEFAULT NULL COMMENT '',
  `Coste_total` DECIMAL(9,2) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`Num_pedido`, `Usuario_idusuario`)  COMMENT '',
  INDEX `fk_Pedidos_Usuario_idx` (`Usuario_idusuario` ASC)  COMMENT '',
  CONSTRAINT `fk_Pedidos_Usuario`
    FOREIGN KEY (`Usuario_idusuario`)
    REFERENCES `proyecto`.`usuarios` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `proyecto`.`detalle_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`detalle_pedido` (
  `Cantidad` INT(11) NULL DEFAULT NULL COMMENT '',
  `codlinea` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `Pedidos_Num_pedido` INT(11) NOT NULL COMMENT '',
  `Producto_IdProducto` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`codlinea`, `Pedidos_Num_pedido`, `Producto_IdProducto`)  COMMENT '',
  INDEX `fk_Detalle pedido_Producto1_idx` (`Producto_IdProducto` ASC)  COMMENT '',
  INDEX `fk_Detalle pedido_Pedidos1` (`Pedidos_Num_pedido` ASC)  COMMENT '',
  CONSTRAINT `fk_Detalle pedido_Pedidos1`
    FOREIGN KEY (`Pedidos_Num_pedido`)
    REFERENCES `proyecto`.`pedidos` (`Num_pedido`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle pedido_Producto1`
    FOREIGN KEY (`Producto_IdProducto`)
    REFERENCES `proyecto`.`producto` (`IdProducto`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
